# Generated by Django 4.1.7 on 2023-03-29 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("userMgmt", "0001_initial"),
        ("tournament", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="user",
            field=models.ForeignKey(
                on_delete=models.SET("deleted_user"), to="userMgmt.customuser"
            ),
        ),
        migrations.AddField(
            model_name="tournament_user",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tournament.tournament"
            ),
        ),
        migrations.AddField(
            model_name="tournament_user",
            name="user",
            field=models.ForeignKey(
                on_delete=models.SET("deleted_user"), to="userMgmt.customuser"
            ),
        ),
        migrations.AddField(
            model_name="tournament_song",
            name="song",
            field=models.ManyToManyField(to="tournament.song"),
        ),
        migrations.AddField(
            model_name="tournament_song",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tournament.tournament"
            ),
        ),
        migrations.AddField(
            model_name="tournament_song",
            name="user",
            field=models.ForeignKey(
                on_delete=models.SET("deleted_user"), to="userMgmt.customuser"
            ),
        ),
        migrations.AddField(
            model_name="tournament_bracket",
            name="tourmament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tournament.tournament"
            ),
        ),
        migrations.AddField(
            model_name="round_vote",
            name="round_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tournament.round"
            ),
        ),
        migrations.AddField(
            model_name="round_vote",
            name="vote_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tournament.vote"
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="bracket_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tournament.tournament_bracket",
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tournament.tournament"
            ),
        ),
        migrations.AddField(
            model_name="resultz",
            name="tournament_song",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="tournament.tournament_song",
            ),
        ),
        migrations.AddField(
            model_name="resultz",
            name="user",
            field=models.ForeignKey(
                on_delete=models.SET("deleted_user"), to="userMgmt.customuser"
            ),
        ),
        migrations.AddField(
            model_name="bracket_winner",
            name="bracket_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tournament.tournament_bracket",
            ),
        ),
        migrations.AddField(
            model_name="bracket_winner",
            name="tournament_song_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tournament.tournament_song",
            ),
        ),
        migrations.AddField(
            model_name="bracket_song",
            name="bracket_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tournament.tournament_bracket",
            ),
        ),
        migrations.AddField(
            model_name="bracket_song",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tournament.tournament"
            ),
        ),
        migrations.AddField(
            model_name="bracket_song",
            name="tournament_song_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tournament.tournament_song",
            ),
        ),
    ]
