# Generated by Django 4.1.7 on 2023-03-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultz",
            name="points",
            field=models.IntegerField(default=0),
        ),
    ]
